### ISSUE TITLE
Technical planning for 2.2 and 2.3

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#21]
Let's follow [our practice of spec-ing out parts of the SOW](https://docs.google.com/document/d/1TONNkmYgKKJJSvHdFLvZpClK5dc20V5WkVnXdpsrHRQ/edit), before we dive into implementation.

All hail the TECH SPEC!

**Comment by reginafcompton** [comment]
It might make sense to break this into two issues. Let's revisit next week.

**Comment by reginafcompton** [comment]
@jeancochrane can you take the lead on assigning this issue to a milestone and/or scraping it for two smaller ones?

**Comment by jeancochrane** [comment]
Oops, I just went ahead and started it @reginafcompton! Here's my draft: https://docs.google.com/document/d/1bAR_cFj4tjADjAZnj0rm5AJ1_vs_ScRp11XRxXjMdbQ/edit?usp=sharing

Anything in particular you think I'm missing? I didn't go into detailed pro/cons because everything here is part of our standard toolkit.
