### ISSUE TITLE
Survey tool: List view of collected data

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#23]
The user should be able to view a list of all run surveys. 

This issue refers to simply setting up the view/route for collected data.

**Comment by beamalsky** [comment]
@jeancochrane, what do you think we should call this route? https://justspaces.datamade.us/surveys/ is surveys that can be run, and I think we need something to distinguish that this view is for the data, not the forms. 

Some options: 

- https://justspaces.datamade.us/submitted <-- this is what fobi does
- https://justspaces.datamade.us/collecteddata
- https://justspaces.datamade.us/surveydata

**Comment by beamalsky** [comment]
Another pattern that Fobi uses, which I don't think is very RESTful:

**https://justspaces.datamade.us/surveys/[Survey ID]** <-- this is where you run the survey
**https://justspaces.datamade.us/surveys/[Survey ID]/submitted** <-- this is where you look at the data you collected with the survey

**Comment by beamalsky** [comment]
I'm imagining the collected data list view has a table of this form:

| Survey Title | Last submitted | 
| -----|------ |

When you click on a survey title, it brings you to a detail view for that survey, which will include ways to interact with individual submissions of that survey.

**Comment by jeancochrane** [comment]
Hmm, this is a tricky question from a design perspective. Since "surveys" and "collected data" basically refer to the same entity in the context of a list view -- "collected data" is really just referring to "surveys that have been run," as I understand it -- part of me feels like the right idiom would be to include a boolean query parameter `?submitted`. This would imply that the table structure would be the same for the "survey" view as it would be for the "collected data" view, in that the parameter would only adjust the query that we run to retrieve the list of surveys.

That being said, it seems like maybe we don't actually want the "survey" table and the "collected data" table to have the same structure, in which case "surveys" and "collected data" are sort of referring to different things. In that case my preference would probably be for `/surveys/submitted/` for the list view and `/surveys/submitted/<survey_id>` for the detail view, which feels like it preserves the fact that "collected data" are essentially a special case of "surveys" while also insisting on the major distinction between them by using separate routes.

What do you think about that @beamalsky ?

**Comment by beamalsky** [comment]
It is tricky, thanks for this! My sense is that we want editing/running a survey and interacting with that survey's submitted data to feel like pretty distinct actions and allow the likely possibility that those tables will have different structures. It makes more sense to me to follow your `/surveys/submitted/` and `/surveys/submitted/<survey_id>` suggestion.

They're also pulling from different models: the editing and run views use Fobi's `FormEntry`, while the submitted data views use PLDP's `Survey`

**Comment by beamalsky** [comment]
Completed by #71
