### ISSUE TITLE
Implement "two-track" survey creation

### ISSUE THREAD

**Issue by reginafcompton** [datamade/just-spaces#46]
Intercept and observational surveys have different requirements. These differences emerge, particularly, in how the surveys handle "counted" data, e.g., "how many people are riding bikes in the park?" vs. "did you ride a bike in the park?" 

Currently, the survey builder offers both types of questions (single vs. multiple count). 

<img width="290" alt="Screen Shot 2019-03-11 at 2 29 32 PM" src="https://user-images.githubusercontent.com/13078679/54148233-40db8200-440a-11e9-8019-6216e81592bd.png">

This can be confusing or "clunky." Instead, the form elements should depend on the type of survey. 

**On the `create` view, let's give users the option to chose one of two "tracks": observational or intercept.**

****

**Important note!** The PLDP handles observational data, but not intercept. For now, users who follow the observational track will also adhere to a strict implementation of PLDP. Alternatively, the intercept surveys will have greater flexible, since intercept surveys aim to capture fine-grained detail, gather opinions, and record non-observable facts.

**Comment by reginafcompton** [comment]
We want to clearly communicate to the user the benefits and disadvantages of departing from the Protocol (e.g., departures from PLDP compromise the share-ability and comparability of survey data). 

For users who select the "intercept" track, we might want some clarifying text, like, “intercept surveys do not follow PLDP....which means...."?

**Comment by beamalsky** [comment]
First steps that @jeancochrane and I determined for this:

Subclass the `django-fobi` FormEntry model in this repo to include new metadata like a `published` boolean (related to #63) and then into two subsubclasses for Intercept and Observational studies. Determine how much this breaks Fobi. Would it be possible to write our own views for the survey creation form, and then keep the Fobi views for the survey element editing functionality? If the answer is no and we're making major changes to Fobi, consider bringing it into the Just Spaces repo instead of maintaining it as a separate fork at https://github.com/datamade/django-fobi
