### ISSUE TITLE
Deleting surveys

### ISSUE THREAD

**Issue by beamalsky** [datamade/just-spaces#84]
While working on #83 I've been thinking about how we want to handle deleting surveys. Currently, the Survey list view has a button to delete SurveyFormEntries. 

I don't think users should be able to do that once a survey is published, since you should be able to look back and rerun a survey once you've started collecting data on it! Maybe we need some kind of additional "active" vs. "inactive" state—for example, if a UCD admin wants to mark when data collection for a survey has concluded—or to let users set a start and (optional) end date on surveys when they're creating them, then only show surveys that are within their active date ranges.

This is related to #54. This is a temp solution I just made for handling deleted surveys we've already collected data for: https://github.com/datamade/just-spaces/pull/83/commits/8e2671fda7f008b82266d2abb5729af5d88a619e

**Comment by jeancochrane** [comment]
If we decide to support deletion, I wonder if we could [add a custom constraint](https://www.fusionbox.com/blog/detail/custom-database-constraints-in-django/594/) to the Survey table with a migration in the `surveys` app? The constraint I'm imagining would be something like:

```sql
ALTER TABLE pdlp_survey
ADD CONSTRAINT form FOREIGN KEY (form_id)
REFERENCES surveys_surveyform (id) ON DELETE CASCADE
```

I'm not really sure if this would work since I don't know if we can reliably say that the `pldp_survey` table will exist before the `surveys_surveyform` table in the app (I would guess that the order of the apps in `INSTALLED_APPS` would determine this). Still, I think it's worth a shot.

**Comment by beamalsky** [comment]
Proposal: We add a new attribute to the SurveyForm model: `is_active`. On new surveys this defaults to true, and once a survey is published it can be marked `active` or`inactive` from the list view and filtered by that value. 

In addition, the Edit Survey list view will include a delete button to fully delete surveys. As these have not been published, they will not have any saved data and can be safely deleted.

**Comment by jeancochrane** [comment]
Sounds good to me!
